// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqlV_jtDCBmb2mzudeurnsPxQR4Ow50DE',
    appId: '1:608723730127:web:cee6f40a30cf752b5141ba',
    messagingSenderId: '608723730127',
    projectId: 'wallets-of-wallets',
    authDomain: 'wallets-of-wallets.firebaseapp.com',
    storageBucket: 'wallets-of-wallets.appspot.com',
    measurementId: 'G-8EEYG1X58W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA03oWfzowRQEDSdGTq2_BCoLnNFyjHX70',
    appId: '1:608723730127:android:4e3f9c409614426f5141ba',
    messagingSenderId: '608723730127',
    projectId: 'wallets-of-wallets',
    storageBucket: 'wallets-of-wallets.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC49jsgM0WePtxy-V5zhPVOue5mYQqr7N8',
    appId: '1:608723730127:ios:05330faa91860e485141ba',
    messagingSenderId: '608723730127',
    projectId: 'wallets-of-wallets',
    storageBucket: 'wallets-of-wallets.appspot.com',
    iosBundleId: 'com.example.firstly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC49jsgM0WePtxy-V5zhPVOue5mYQqr7N8',
    appId: '1:608723730127:ios:76f59528eed5170f5141ba',
    messagingSenderId: '608723730127',
    projectId: 'wallets-of-wallets',
    storageBucket: 'wallets-of-wallets.appspot.com',
    iosBundleId: 'com.example.walletsOfWallets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqlV_jtDCBmb2mzudeurnsPxQR4Ow50DE',
    appId: '1:608723730127:web:89a25a9558b03ecc5141ba',
    messagingSenderId: '608723730127',
    projectId: 'wallets-of-wallets',
    authDomain: 'wallets-of-wallets.firebaseapp.com',
    storageBucket: 'wallets-of-wallets.appspot.com',
    measurementId: 'G-K39FL170N8',
  );
}
